### ISSUE TITLE
Preview de la app

### ISSUE THREAD

**Issue by MatiasOS** [tandil-dev/frontend-infraction#35]
**Describe the bug**
Al obtener la vista previa de la app, se muestra un mensaje default de React
**To Reproduce**
1. Go to Whatsapp
2. Paste https://centinela.tandil.dev
3. Ver la vista previa

**Expected behavior**
Descripción acorde al proyecto

**Screenshots**
![preview](https://user-images.githubusercontent.com/5481398/84091774-daa62c00-a9cb-11ea-84e2-90158158006f.png)

**Desktop (please complete the following information):**
**Smartphone (please complete the following information):**

**Additional context**

**Comment by fedelmar** [comment]
Servirá cambiar la descripción?
https://github.com/tandil-dev/frontend-infraction/pull/38

**Comment by MatiasOS** [comment]
closed by #38. Check #51
