### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by MatiasOS** [tandil-dev/frontend-infraction#52]
**Describe the bug**
Tenemos un montón de Warnings en la app. 
**To Reproduce**
1. yarn run dev
2. Mirar la consola

**Expected behavior**
Estaría bueno que no esten los warnings :clown_face: 
**Screenshots**
![warnings](https://user-images.githubusercontent.com/5481398/84498914-e1f95e00-ac87-11ea-9082-2e17acbef2f5.png)

**Comment by fedelmar** [comment]
Resuelto en https://github.com/tandil-dev/frontend-infraction/pull/69
