### ISSUE TITLE
Menú navegación inf. | Texto  

### ISSUE THREAD

**Issue by SabrinaDominguez** [tandil-dev/frontend-infraction#63]
- [ ] Agregar el texto debajo de los íconos (botones) del menú de navegación inferior: (orden de izquierda a derecha).
- "Perfil"
- "Reportar" ó "Denunciar"
- "Más"

Justificación: la persona entiende mejor, cuando lee y mira, "qué puede hacer" con ese botón.

![Home cuenta personal](https://user-images.githubusercontent.com/65744576/86041862-b662cb80-ba1c-11ea-8ef5-9a0c622c3f1b.png)

**Comment by fedelmar** [comment]
https://github.com/tandil-dev/frontend-infraction/pull/69
