### ISSUE TITLE
Título "Denunciar una Infracción"

### ISSUE THREAD

**Issue by SabrinaDominguez** [tandil-dev/frontend-infraction#64]
- [x] Agregar el texto/título "Denunciar/Reportar una infracción" en el medio del header y de la secuencia de pasos (1 cargar datos; paso 2...)

Justificación: Con ese texto/título le indicamos y **ubicamos** al usuario en qué lugar se encuentra de la aplicación. En este caso, estaría dentro del flujo para reportar una infracción.

![Texto- Denunciar una infraccion](https://user-images.githubusercontent.com/65744576/86046275-53c0fe00-ba23-11ea-863a-0b463719f885.png)

**Comment by fedelmar** [comment]
Echo :D
