### ISSUE TITLE
Agregar título/texto

### ISSUE THREAD

**Issue by SabrinaDominguez** [tandil-dev/frontend-infraction#65]
- [x] Habría que agregar un titulo/texto arriba de los botones para subir las imágenes, algo así como:
"Prueba fotográfica o vídeo".
Justificación: De esta forma le informamos al usuario la información (valga la redundancia) de las pruebas que tiene que aportar para reportar la infracción. 

- [x] Unificar las mismas palabras de los botones: o bien usamos siempre "seleccionar" ó usamos "elegir".

![Agregar titulo](https://user-images.githubusercontent.com/65744576/86046851-540dc900-ba24-11ea-9860-7f16e663b9c7.png)

**Comment by fedelmar** [comment]
Agregue el titulo, pero el tema de seleccionar los archivos creo que es cuestión del navegador o el sistema operativo. El mio lo dice en ingles y es el mismo para los dos.

**Comment by SabrinaDominguez** [comment]
Si, lo habíamos charlado el otro dia en la reunion

**Comment by fedelmar** [comment]
Listo entonces!
